version: '3'

services:

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9090:9000
    deploy:
      placement:
        constraints: [node.role == manager]


  viz:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9080:8080
    deploy:
      placement:
        constraints: [node.role == manager]
